
### Add a New Post
POST http://localhost:3000/post
Content-Type: application/json

{
	"title": "My first post",
	"content": "Hello world",
	"sender": "user123"
}

### Get All Posts
GET http://localhost:3000/post

### Get a Post by ID (replace :id)
GET http://localhost:3000/post/694d81391c79b2a3679f581c