
### Add a New Post
POST http://localhost:3000/post
Content-Type: application/json

{
	"title": "My first post",
	"content": "Hello world",
	"sender": "user123"
}

### Get All Posts
GET http://localhost:3000/post

### Get a Post by ID (replace :id)
GET http://localhost:3000/post/96fb7857cf27a620b7

### Get Posts by Sender
GET http://localhost:3000/post?sender=user123

### Update a Post (replace :id)
PUT http://localhost:3000/post/694d81391c79b2a3679f581c
Content-Type: application/json

{
	"title": "Updated title",
	"content": "Updated content",
	"sender": "user123"
}